---
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
---
title: [Firebrick's Personal Website]
description: [Firebrick about the Project Management]
show_downloads: [false]
google_analytics: [ID-234323554]
url: "https://firebrick.github.io"
